/*
 * DO NOT EDIT THIS FILE - it is generated by wGLADE.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
//#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *alignment1;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *new1;
  GtkWidget *separatore1;
  GtkWidget *load1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *close1;
  GtkWidget *separatore2;
  GtkWidget *print1;
  GtkWidget *separatore3;
  GtkWidget *exit1;
  GtkWidget *edit1;
  GtkWidget *edit1_menu;
  GtkAccelGroup *edit1_menu_accels;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *separatore5;
  GtkWidget *find1;
  GtkWidget *find_next1;
  GtkWidget *replace1;
  GtkWidget *separatore4;
  GtkWidget *select_all1;
  GtkWidget *invert_selection1;
  GtkWidget *run1;
  GtkWidget *run1_menu;
  GtkAccelGroup *run1_menu_accels;
  GtkWidget *execute1;
  GtkWidget *debug1;
  GtkWidget *stop1;
  GtkWidget *item1;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *manual1;
  GtkWidget *about_ide1;
  GtkWidget *toolbar3;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button10;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *combo1;
  GtkWidget *combo_entry1;
  GtkWidget *button9;
  GtkWidget *hpaned1;
  GtkWidget *notebook2;
  GtkWidget *list1;
  GtkWidget *label1;
  GtkWidget *list2;
  GtkWidget *label2;
  GtkWidget *list3;
  GtkWidget *label3;
  GtkWidget *scrolledwindow4;
  GtkWidget *text3;
  GtkWidget *label4;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *vpaned1;
  GtkWidget *scrolledwindow2;
  GtkWidget *text1;
  GtkWidget *scrolledwindow3;
  GtkWidget *text2;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window1, "window1");
  gtk_object_set_data (GTK_OBJECT (window1), "window1", window1);
  gtk_widget_set_usize (window1, 800, 600);
  gtk_window_set_title (GTK_WINDOW (window1), "ide");
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (window1), TRUE);

  alignment1 = gtk_alignment_new (0,5, 0,5, 1, 1);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_ref (alignment1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "alignment1", alignment1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (window1), alignment1);
  gtk_widget_set_usize (alignment1, 322, 120);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  file1 = gtk_menu_item_new_with_label ("File");
  gtk_widget_set_name (file1, "file1");
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (menubar1), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_set_name (file1_menu, "file1_menu");
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window1), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  new1 = gtk_menu_item_new_with_label ("new");
  gtk_widget_set_name (new1, "new1");
  gtk_widget_ref (new1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "new1", new1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (file1_menu), new1);

  separatore1 = gtk_menu_item_new ();
  gtk_widget_set_name (separatore1, "separatore1");
  gtk_widget_ref (separatore1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "separatore1", separatore1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separatore1);
  gtk_container_add (GTK_CONTAINER (file1_menu), separatore1);
  gtk_widget_set_sensitive (separatore1, FALSE);

  load1 = gtk_menu_item_new_with_label ("load");
  gtk_widget_set_name (load1, "load1");
  gtk_widget_ref (load1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "load1", load1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load1);
  gtk_container_add (GTK_CONTAINER (file1_menu), load1);

  save1 = gtk_menu_item_new_with_label ("save");
  gtk_widget_set_name (save1, "save1");
  gtk_widget_ref (save1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "save1", save1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (file1_menu), save1);

  save_as1 = gtk_menu_item_new_with_label ("save as");
  gtk_widget_set_name (save_as1, "save_as1");
  gtk_widget_ref (save_as1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "save_as1", save_as1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (file1_menu), save_as1);

  close1 = gtk_menu_item_new_with_label ("close");
  gtk_widget_set_name (close1, "close1");
  gtk_widget_ref (close1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "close1", close1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (close1);
  gtk_container_add (GTK_CONTAINER (file1_menu), close1);

  separatore2 = gtk_menu_item_new ();
  gtk_widget_set_name (separatore2, "separatore2");
  gtk_widget_ref (separatore2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "separatore2", separatore2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separatore2);
  gtk_container_add (GTK_CONTAINER (file1_menu), separatore2);
  gtk_widget_set_sensitive (separatore2, FALSE);

  print1 = gtk_menu_item_new_with_label ("print");
  gtk_widget_set_name (print1, "print1");
  gtk_widget_ref (print1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "print1", print1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (print1);
  gtk_container_add (GTK_CONTAINER (file1_menu), print1);

  separatore3 = gtk_menu_item_new ();
  gtk_widget_set_name (separatore3, "separatore3");
  gtk_widget_ref (separatore3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "separatore3", separatore3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separatore3);
  gtk_container_add (GTK_CONTAINER (file1_menu), separatore3);
  gtk_widget_set_sensitive (separatore3, FALSE);

  exit1 = gtk_menu_item_new_with_label ("exit");
  gtk_widget_set_name (exit1, "exit1");
  gtk_widget_ref (exit1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "exit1", exit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), exit1);

  edit1 = gtk_menu_item_new_with_label ("Edit");
  gtk_widget_set_name (edit1, "edit1");
  gtk_widget_ref (edit1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "edit1", edit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit1);
  gtk_container_add (GTK_CONTAINER (menubar1), edit1);

  edit1_menu = gtk_menu_new ();
  gtk_widget_set_name (edit1_menu, "edit1_menu");
  gtk_widget_ref (edit1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window1), "edit1_menu", edit1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (edit1), edit1_menu);
  edit1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (edit1_menu));

  cut1 = gtk_menu_item_new_with_label ("cut");
  gtk_widget_set_name (cut1, "cut1");
  gtk_widget_ref (cut1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "cut1", cut1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), cut1);

  copy1 = gtk_menu_item_new_with_label ("copy");
  gtk_widget_set_name (copy1, "copy1");
  gtk_widget_ref (copy1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "copy1", copy1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), copy1);

  paste1 = gtk_menu_item_new_with_label ("paste");
  gtk_widget_set_name (paste1, "paste1");
  gtk_widget_ref (paste1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "paste1", paste1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), paste1);

  separatore5 = gtk_menu_item_new ();
  gtk_widget_set_name (separatore5, "separatore5");
  gtk_widget_ref (separatore5);
  gtk_object_set_data_full (GTK_OBJECT (window1), "separatore5", separatore5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separatore5);
  gtk_container_add (GTK_CONTAINER (edit1_menu), separatore5);
  gtk_widget_set_sensitive (separatore5, FALSE);

  find1 = gtk_menu_item_new_with_label ("find");
  gtk_widget_set_name (find1, "find1");
  gtk_widget_ref (find1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "find1", find1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (find1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), find1);

  find_next1 = gtk_menu_item_new_with_label ("find next");
  gtk_widget_set_name (find_next1, "find_next1");
  gtk_widget_ref (find_next1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "find_next1", find_next1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (find_next1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), find_next1);
  gtk_widget_add_accelerator (find_next1, "activate", accel_group,
                              GDK_F3, 0,
                              GTK_ACCEL_VISIBLE);

  replace1 = gtk_menu_item_new_with_label ("replace");
  gtk_widget_set_name (replace1, "replace1");
  gtk_widget_ref (replace1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "replace1", replace1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (replace1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), replace1);

  separatore4 = gtk_menu_item_new ();
  gtk_widget_set_name (separatore4, "separatore4");
  gtk_widget_ref (separatore4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "separatore4", separatore4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separatore4);
  gtk_container_add (GTK_CONTAINER (edit1_menu), separatore4);
  gtk_widget_set_sensitive (separatore4, FALSE);

  select_all1 = gtk_menu_item_new_with_label ("select all");
  gtk_widget_set_name (select_all1, "select_all1");
  gtk_widget_ref (select_all1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "select_all1", select_all1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (select_all1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), select_all1);

  invert_selection1 = gtk_menu_item_new_with_label ("invert selection");
  gtk_widget_set_name (invert_selection1, "invert_selection1");
  gtk_widget_ref (invert_selection1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "invert_selection1", invert_selection1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (invert_selection1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), invert_selection1);

  run1 = gtk_menu_item_new_with_label ("Run");
  gtk_widget_set_name (run1, "run1");
  gtk_widget_ref (run1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "run1", run1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (run1);
  gtk_container_add (GTK_CONTAINER (menubar1), run1);

  run1_menu = gtk_menu_new ();
  gtk_widget_set_name (run1_menu, "run1_menu");
  gtk_widget_ref (run1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window1), "run1_menu", run1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (run1), run1_menu);
  run1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (run1_menu));

  execute1 = gtk_menu_item_new_with_label ("execute");
  gtk_widget_set_name (execute1, "execute1");
  gtk_widget_ref (execute1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "execute1", execute1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (execute1);
  gtk_container_add (GTK_CONTAINER (run1_menu), execute1);

  debug1 = gtk_menu_item_new_with_label ("debug");
  gtk_widget_set_name (debug1, "debug1");
  gtk_widget_ref (debug1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "debug1", debug1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (debug1);
  gtk_container_add (GTK_CONTAINER (run1_menu), debug1);

  stop1 = gtk_menu_item_new_with_label ("stop");
  gtk_widget_set_name (stop1, "stop1");
  gtk_widget_ref (stop1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "stop1", stop1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (stop1);
  gtk_container_add (GTK_CONTAINER (run1_menu), stop1);

  item1 = gtk_menu_item_new_with_label ("item1");
  gtk_widget_set_name (item1, "item1");
  gtk_widget_ref (item1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "item1", item1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (item1);
  gtk_container_add (GTK_CONTAINER (run1_menu), item1);

  help1 = gtk_menu_item_new_with_label ("Help");
  gtk_widget_set_name (help1, "help1");
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar1), help1);

  help1_menu = gtk_menu_new ();
  gtk_widget_set_name (help1_menu, "help1_menu");
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (window1), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  manual1 = gtk_menu_item_new_with_label ("manual");
  gtk_widget_set_name (manual1, "manual1");
  gtk_widget_ref (manual1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "manual1", manual1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manual1);
  gtk_container_add (GTK_CONTAINER (help1_menu), manual1);

  about_ide1 = gtk_menu_item_new_with_label ("about ide");
  gtk_widget_set_name (about_ide1, "about_ide1");
  gtk_widget_ref (about_ide1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "about_ide1", about_ide1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about_ide1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about_ide1);

  toolbar3 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_set_name (toolbar3, "toolbar3");
  gtk_widget_ref (toolbar3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "toolbar3", toolbar3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar3);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar3, FALSE, FALSE, 0);

  tmp_toolbar_icon = create_pixmap (window1, "filenew.xpm");
  button1 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "new",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button1, "button1");
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);

  tmp_toolbar_icon = create_pixmap (window1, "folder.xpm");
  button2 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "load",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button2, "button2");
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);

  tmp_toolbar_icon = create_pixmap (window1, "filesave.xpm");
  button3 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "save",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button3, "button3");
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);

  tmp_toolbar_icon = create_pixmap (window1, "exel.xpm");
  button10 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "close",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button10, "button10");
  gtk_widget_ref (button10);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button10", button10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button10);

  tmp_toolbar_icon = create_pixmap (window1, "undo.xpm");
  button4 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "undo",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button4, "button4");
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);

  tmp_toolbar_icon = create_pixmap (window1, "redo.xpm");
  button5 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "redo",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button5, "button5");
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);

  tmp_toolbar_icon = create_pixmap (window1, "1rightarrow.xpm");
  button6 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "run",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button6, "button6");
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);

  tmp_toolbar_icon = create_pixmap (window1, "next.xpm");
  button7 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "debug",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button7, "button7");
  gtk_widget_ref (button7);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button7", button7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button7);

  tmp_toolbar_icon = create_pixmap (window1, "stop.xpm");
  button8 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "stop",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button8, "button8");
  gtk_widget_ref (button8);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button8", button8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button8);

  combo1 = gtk_combo_new ();
  gtk_widget_set_name (combo1, "combo1");
  gtk_widget_ref (combo1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "combo1", combo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo1);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar3), combo1, NULL, NULL);

  combo_entry1 = GTK_COMBO (combo1)->entry;
  gtk_widget_set_name (combo_entry1, "combo_entry1");
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);

  tmp_toolbar_icon = create_pixmap (window1, "find.xpm");
  button9 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "find",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (button9, "button9");
  gtk_widget_ref (button9);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button9", button9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button9);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_set_name (hpaned1, "hpaned1");
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_widget_set_usize (hpaned1, 322, 42);
  GTK_WIDGET_SET_FLAGS (hpaned1, GTK_CAN_DEFAULT);
  gtk_paned_set_gutter_size (GTK_PANED (hpaned1), -858993460);
  gtk_paned_set_position (GTK_PANED (hpaned1), 180);

  notebook2 = gtk_notebook_new ();
  gtk_widget_set_name (notebook2, "notebook2");
  gtk_widget_ref (notebook2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "notebook2", notebook2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook2);
  gtk_paned_pack1 (GTK_PANED (hpaned1), notebook2, FALSE, TRUE);
  gtk_widget_set_usize (notebook2, 132, 31);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook2), GTK_POS_BOTTOM);

  list1 = gtk_list_new ();
  gtk_widget_set_name (list1, "list1");
  gtk_widget_ref (list1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "list1", list1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (list1);
  gtk_container_add (GTK_CONTAINER (notebook2), list1);

  label1 = gtk_label_new ("buffers");
  gtk_widget_set_name (label1, "label1");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label1);

  list2 = gtk_list_new ();
  gtk_widget_set_name (list2, "list2");
  gtk_widget_ref (list2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "list2", list2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (list2);
  gtk_container_add (GTK_CONTAINER (notebook2), list2);

  label2 = gtk_label_new ("rutines");
  gtk_widget_set_name (label2, "label2");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label2);

  list3 = gtk_list_new ();
  gtk_widget_set_name (list3, "list3");
  gtk_widget_ref (list3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "list3", list3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (list3);
  gtk_container_add (GTK_CONTAINER (notebook2), list3);

  label3 = gtk_label_new ("tools");
  gtk_widget_set_name (label3, "label3");
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label3);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow4, "scrolledwindow4");
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  text3 = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (text3, "text3");
  gtk_widget_ref (text3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "text3", text3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), text3);

  label4 = gtk_label_new ("help");
  gtk_widget_set_name (label4, "label4");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label4);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), scrolledwindow1, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport1, "viewport1");
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_set_name (vpaned1, "vpaned1");
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_container_add (GTK_CONTAINER (viewport1), vpaned1);
  gtk_paned_set_gutter_size (GTK_PANED (vpaned1), -858993460);
  gtk_paned_set_position (GTK_PANED (vpaned1), 430);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_paned_pack1 (GTK_PANED (vpaned1), scrolledwindow2, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  text1 = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (text1, "text1");
  gtk_widget_ref (text1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "text1", text1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), text1);
  gtk_text_set_editable (GTK_TEXT (text1), TRUE);
  gtk_text_insert (GTK_TEXT (text1), NULL, NULL, NULL,
                   "prova", 5);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_paned_pack2 (GTK_PANED (vpaned1), scrolledwindow3, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  text2 = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (text2, "text2");
  gtk_widget_ref (text2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "text2", text2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), text2);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar1, "statusbar1");
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (statusbar1), 1);

  gtk_signal_connect (GTK_OBJECT (window1), "destroy",
                      GTK_SIGNAL_FUNC (on_window1_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (file1), "activate",
                      GTK_SIGNAL_FUNC (on_file1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (new1), "activate",
                      GTK_SIGNAL_FUNC (on_new1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (load1), "activate",
                      GTK_SIGNAL_FUNC (on_load1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save1), "activate",
                      GTK_SIGNAL_FUNC (on_save1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save_as1), "activate",
                      GTK_SIGNAL_FUNC (on_save_as1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (close1), "activate",
                      GTK_SIGNAL_FUNC (on_close1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (print1), "activate",
                      GTK_SIGNAL_FUNC (on_print1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit1), "activate",
                      GTK_SIGNAL_FUNC (on_exit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit1), "activate",
                      GTK_SIGNAL_FUNC (on_edit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cut1), "activate",
                      GTK_SIGNAL_FUNC (on_cut1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (copy1), "activate",
                      GTK_SIGNAL_FUNC (on_copy1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (paste1), "activate",
                      GTK_SIGNAL_FUNC (on_paste1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (find1), "activate",
                      GTK_SIGNAL_FUNC (on_find1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (find_next1), "activate",
                      GTK_SIGNAL_FUNC (on_find_next1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (replace1), "activate",
                      GTK_SIGNAL_FUNC (on_replace1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (select_all1), "activate",
                      GTK_SIGNAL_FUNC (on_select_all1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (invert_selection1), "activate",
                      GTK_SIGNAL_FUNC (on_invert_selection1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (run1), "activate",
                      GTK_SIGNAL_FUNC (on_run1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (execute1), "activate",
                      GTK_SIGNAL_FUNC (on_execute1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (debug1), "activate",
                      GTK_SIGNAL_FUNC (on_debug1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (stop1), "activate",
                      GTK_SIGNAL_FUNC (on_stop1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (item1), "activate",
                      GTK_SIGNAL_FUNC (on_item1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (help1), "activate",
                      GTK_SIGNAL_FUNC (on_help1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (manual1), "activate",
                      GTK_SIGNAL_FUNC (on_manual1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about_ide1), "activate",
                      GTK_SIGNAL_FUNC (on_about_ide1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_button1_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (on_button2_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_button3_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button10), "clicked",
                      GTK_SIGNAL_FUNC (on_button10_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_button4_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (on_button5_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (on_button6_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button7), "clicked",
                      GTK_SIGNAL_FUNC (on_button7_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button8), "clicked",
                      GTK_SIGNAL_FUNC (on_button8_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button9), "clicked",
                      GTK_SIGNAL_FUNC (on_button9_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (list1), "select_child",
                      GTK_SIGNAL_FUNC (on_list1_select_child),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (list2), "select_child",
                      GTK_SIGNAL_FUNC (on_list2_select_child),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (list3), "select_child",
                      GTK_SIGNAL_FUNC (on_list3_select_child),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

GtkWidget*
create_fileselection1 (void)
{
  GtkWidget *fileselection1;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  fileselection1 = gtk_file_selection_new ("Seleziona file");
  gtk_widget_set_name (fileselection1, "fileselection1");
  gtk_object_set_data (GTK_OBJECT (fileselection1), "fileselection1", fileselection1);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection1), 10);
  GTK_WIDGET_SET_FLAGS (fileselection1, GTK_CAN_FOCUS);
//  GTK_WINDOW (fileselection1)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_modal (GTK_WINDOW (fileselection1), TRUE);

  ok_button1 = GTK_FILE_SELECTION (fileselection1)->ok_button;
  gtk_widget_set_name (ok_button1, "ok_button1");
  gtk_object_set_data (GTK_OBJECT (fileselection1), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (fileselection1)->cancel_button;
  gtk_widget_set_name (cancel_button1, "cancel_button1");
  gtk_object_set_data (GTK_OBJECT (fileselection1), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button1_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button1_clicked),
                      NULL);

  return fileselection1;
}

