/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GdkPixbuf *main_window_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *nuovo1;
  GtkWidget *apri1;
  GtkWidget *salva1;
  GtkWidget *salva_come1;
  GtkWidget *close1;
  GtkWidget *image61;
  GtkWidget *separatore6;
  GtkWidget *anteprima_di_stampa1;
  GtkWidget *image62;
  GtkWidget *stampa1;
  GtkWidget *image63;
  GtkWidget *separatormenuitem1;
  GtkWidget *esci1;
  GtkWidget *menuitem5;
  GtkWidget *menuitem5_menu;
  GtkWidget *undo2;
  GtkWidget *image64;
  GtkWidget *redo2;
  GtkWidget *image65;
  GtkWidget *separatore3;
  GtkWidget *taglia1;
  GtkWidget *copia1;
  GtkWidget *incolla1;
  GtkWidget *elimina1;
  GtkWidget *separatore4;
  GtkWidget *trova2;
  GtkWidget *image66;
  GtkWidget *trova_e_sostituisci1;
  GtkWidget *image67;
  GtkWidget *separatore5;
  GtkWidget *seleziona_tutto1;
  GtkWidget *inverti_selezione1;
  GtkWidget *run1;
  GtkWidget *run1_menu;
  GtkWidget *execute1;
  GtkWidget *image68;
  GtkWidget *debug1;
  GtkWidget *image69;
  GtkWidget *stop1;
  GtkWidget *image70;
  GtkWidget *menuitem7;
  GtkWidget *menuitem7_menu;
  GtkWidget *informazioni1;
  GtkWidget *toolbar1;
  gint tmp_toolbar_icon_size;
  GtkWidget *toolbutton_nuovo;
  GtkWidget *separatortoolitem1;
  GtkWidget *toolbutton_load;
  GtkWidget *toolbutton_salva;
  GtkWidget *toolbutton_chiudi;
  GtkWidget *separatortoolitem2;
  GtkWidget *toolbutton_undo;
  GtkWidget *toolbutton_redo;
  GtkWidget *separatortoolitem3;
  GtkWidget *tmp_image;
  GtkWidget *toolbutton_execute;
  GtkWidget *toolbutton_debug;
  GtkWidget *toolbutton_stop;
  GtkWidget *eventbox1;
  GtkWidget *hpaned1;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview2;
  GtkWidget *label1;
  GtkWidget *vbox3;
  GtkWidget *comboboxentry3;
  GtkWidget *toolbar2;
  GtkWidget *toolbutton1;
  GtkWidget *separatortoolitem4;
  GtkWidget *toolbutton2;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview1;
  GtkWidget *label2;
  GtkWidget *vbox4;
  GtkWidget *toolbar3;
  GtkWidget *toolbutton7;
  GtkWidget *toolbutton8;
  GtkWidget *toolbutton9;
  GtkWidget *scrolledwindow6;
  GtkWidget *treeview3;
  GtkWidget *label3;
  GtkWidget *scrolledwindow7;
  GtkWidget *textview1;
  GtkWidget *label4;
  GtkWidget *vpaned1;
  GtkWidget *scrolledwindow1;
  GtkWidget *textview_code;
  GtkWidget *scrolledwindow2;
  GtkWidget *textview_output;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (main_window, "main_window");
  GTK_WIDGET_SET_FLAGS (main_window, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (main_window, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (main_window), _("ide"));
  gtk_window_set_default_size (GTK_WINDOW (main_window), 800, 600);
  main_window_icon_pixbuf = create_pixbuf ("SdlBasic.ico");
  if (main_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (main_window), main_window_icon_pixbuf);
      gdk_pixbuf_unref (main_window_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_window), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_set_name (menuitem4, "menuitem4");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem4_menu, "menuitem4_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  nuovo1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_set_name (nuovo1, "nuovo1");
  gtk_widget_show (nuovo1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), nuovo1);

  apri1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_set_name (apri1, "apri1");
  gtk_widget_show (apri1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), apri1);

  salva1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_set_name (salva1, "salva1");
  gtk_widget_show (salva1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), salva1);

  salva_come1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_set_name (salva_come1, "salva_come1");
  gtk_widget_show (salva_come1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), salva_come1);

  close1 = gtk_image_menu_item_new_with_mnemonic (_("_Chiudi"));
  gtk_widget_set_name (close1, "close1");
  gtk_widget_show (close1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), close1);
  gtk_widget_add_accelerator (close1, "activate", accel_group,
                              GDK_X, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image61 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image61, "image61");
  gtk_widget_show (image61);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (close1), image61);

  separatore6 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separatore6, "separatore6");
  gtk_widget_show (separatore6);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separatore6);
  gtk_widget_set_sensitive (separatore6, FALSE);

  anteprima_di_stampa1 = gtk_image_menu_item_new_with_mnemonic (_("Antepri_ma di stampa"));
  gtk_widget_set_name (anteprima_di_stampa1, "anteprima_di_stampa1");
  gtk_widget_show (anteprima_di_stampa1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), anteprima_di_stampa1);

  image62 = gtk_image_new_from_stock ("gtk-print-preview", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image62, "image62");
  gtk_widget_show (image62);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (anteprima_di_stampa1), image62);

  stampa1 = gtk_image_menu_item_new_with_mnemonic (_("Stam_pa"));
  gtk_widget_set_name (stampa1, "stampa1");
  gtk_widget_show (stampa1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), stampa1);

  image63 = gtk_image_new_from_stock ("gtk-print", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image63, "image63");
  gtk_widget_show (image63);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (stampa1), image63);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separatormenuitem1, "separatormenuitem1");
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  esci1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (esci1, "esci1");
  gtk_widget_show (esci1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), esci1);

  menuitem5 = gtk_menu_item_new_with_mnemonic (_("_Modifica"));
  gtk_widget_set_name (menuitem5, "menuitem5");
  gtk_widget_show (menuitem5);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem5);

  menuitem5_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem5_menu, "menuitem5_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem5), menuitem5_menu);

  undo2 = gtk_image_menu_item_new_with_mnemonic (_("_Undo"));
  gtk_widget_set_name (undo2, "undo2");
  gtk_widget_show (undo2);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), undo2);

  image64 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image64, "image64");
  gtk_widget_show (image64);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (undo2), image64);

  redo2 = gtk_image_menu_item_new_with_mnemonic (_("_Redo"));
  gtk_widget_set_name (redo2, "redo2");
  gtk_widget_show (redo2);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), redo2);

  image65 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image65, "image65");
  gtk_widget_show (image65);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (redo2), image65);

  separatore3 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separatore3, "separatore3");
  gtk_widget_show (separatore3);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), separatore3);
  gtk_widget_set_sensitive (separatore3, FALSE);

  taglia1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_set_name (taglia1, "taglia1");
  gtk_widget_show (taglia1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), taglia1);

  copia1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_set_name (copia1, "copia1");
  gtk_widget_show (copia1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), copia1);

  incolla1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_set_name (incolla1, "incolla1");
  gtk_widget_show (incolla1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), incolla1);

  elimina1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_set_name (elimina1, "elimina1");
  gtk_widget_show (elimina1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), elimina1);

  separatore4 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separatore4, "separatore4");
  gtk_widget_show (separatore4);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), separatore4);
  gtk_widget_set_sensitive (separatore4, FALSE);

  trova2 = gtk_image_menu_item_new_with_mnemonic (_("_Trova"));
  gtk_widget_set_name (trova2, "trova2");
  gtk_widget_show (trova2);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), trova2);

  image66 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image66, "image66");
  gtk_widget_show (image66);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (trova2), image66);

  trova_e_sostituisci1 = gtk_image_menu_item_new_with_mnemonic (_("Trova e sostit_uisci"));
  gtk_widget_set_name (trova_e_sostituisci1, "trova_e_sostituisci1");
  gtk_widget_show (trova_e_sostituisci1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), trova_e_sostituisci1);

  image67 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image67, "image67");
  gtk_widget_show (image67);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (trova_e_sostituisci1), image67);

  separatore5 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separatore5, "separatore5");
  gtk_widget_show (separatore5);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), separatore5);
  gtk_widget_set_sensitive (separatore5, FALSE);

  seleziona_tutto1 = gtk_menu_item_new_with_mnemonic (_("_Seleziona Tutto"));
  gtk_widget_set_name (seleziona_tutto1, "seleziona_tutto1");
  gtk_widget_show (seleziona_tutto1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), seleziona_tutto1);

  inverti_selezione1 = gtk_menu_item_new_with_mnemonic (_("Inverti selezione"));
  gtk_widget_set_name (inverti_selezione1, "inverti_selezione1");
  gtk_widget_show (inverti_selezione1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), inverti_selezione1);

  run1 = gtk_menu_item_new_with_mnemonic (_("_Run"));
  gtk_widget_set_name (run1, "run1");
  gtk_widget_show (run1);
  gtk_container_add (GTK_CONTAINER (menubar1), run1);

  run1_menu = gtk_menu_new ();
  gtk_widget_set_name (run1_menu, "run1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (run1), run1_menu);

  execute1 = gtk_image_menu_item_new_with_mnemonic (_("_Execute"));
  gtk_widget_set_name (execute1, "execute1");
  gtk_widget_show (execute1);
  gtk_container_add (GTK_CONTAINER (run1_menu), execute1);
  gtk_widget_add_accelerator (execute1, "activate", accel_group,
                              GDK_F5, 0,
                              GTK_ACCEL_VISIBLE);

  image68 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image68, "image68");
  gtk_widget_show (image68);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (execute1), image68);

  debug1 = gtk_image_menu_item_new_with_mnemonic (_("_Debug"));
  gtk_widget_set_name (debug1, "debug1");
  gtk_widget_show (debug1);
  gtk_container_add (GTK_CONTAINER (run1_menu), debug1);
  gtk_widget_add_accelerator (debug1, "activate", accel_group,
                              GDK_F6, 0,
                              GTK_ACCEL_VISIBLE);

  image69 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image69, "image69");
  gtk_widget_show (image69);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (debug1), image69);

  stop1 = gtk_image_menu_item_new_with_mnemonic (_("_Stop"));
  gtk_widget_set_name (stop1, "stop1");
  gtk_widget_show (stop1);
  gtk_container_add (GTK_CONTAINER (run1_menu), stop1);
  gtk_widget_add_accelerator (stop1, "activate", accel_group,
                              GDK_C, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image70 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image70, "image70");
  gtk_widget_show (image70);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (stop1), image70);

  menuitem7 = gtk_menu_item_new_with_mnemonic (_("A_iuto"));
  gtk_widget_set_name (menuitem7, "menuitem7");
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem7);

  menuitem7_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem7_menu, "menuitem7_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menuitem7_menu);

  informazioni1 = gtk_menu_item_new_with_mnemonic (_("I_nformazioni"));
  gtk_widget_set_name (informazioni1, "informazioni1");
  gtk_widget_show (informazioni1);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), informazioni1);
  gtk_widget_add_accelerator (informazioni1, "activate", accel_group,
                              GDK_F1, 0,
                              GTK_ACCEL_VISIBLE);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  toolbutton_nuovo = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-new");
  gtk_widget_set_name (toolbutton_nuovo, "toolbutton_nuovo");
  gtk_widget_show (toolbutton_nuovo);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_nuovo);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem1, "separatortoolitem1");
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem1);

  toolbutton_load = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-open");
  gtk_widget_set_name (toolbutton_load, "toolbutton_load");
  gtk_widget_show (toolbutton_load);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_load);

  toolbutton_salva = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-save");
  gtk_widget_set_name (toolbutton_salva, "toolbutton_salva");
  gtk_widget_show (toolbutton_salva);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_salva);

  toolbutton_chiudi = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (toolbutton_chiudi, "toolbutton_chiudi");
  gtk_widget_show (toolbutton_chiudi);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_chiudi);

  separatortoolitem2 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem2, "separatortoolitem2");
  gtk_widget_show (separatortoolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem2);

  toolbutton_undo = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-undo");
  gtk_widget_set_name (toolbutton_undo, "toolbutton_undo");
  gtk_widget_show (toolbutton_undo);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_undo);

  toolbutton_redo = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-redo");
  gtk_widget_set_name (toolbutton_redo, "toolbutton_redo");
  gtk_widget_show (toolbutton_redo);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_redo);

  separatortoolitem3 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem3, "separatortoolitem3");
  gtk_widget_show (separatortoolitem3);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem3);

  tmp_image = create_pixmap (main_window, "1rightarrow.xpm");
  gtk_widget_show (tmp_image);
  toolbutton_execute = (GtkWidget*) gtk_tool_button_new (tmp_image, _("execute"));
  gtk_widget_set_name (toolbutton_execute, "toolbutton_execute");
  gtk_widget_show (toolbutton_execute);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_execute);

  tmp_image = create_pixmap (main_window, "next.xpm");
  gtk_widget_show (tmp_image);
  toolbutton_debug = (GtkWidget*) gtk_tool_button_new (tmp_image, _("debug"));
  gtk_widget_set_name (toolbutton_debug, "toolbutton_debug");
  gtk_widget_show (toolbutton_debug);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_debug);
  gtk_tool_item_set_is_important (GTK_TOOL_ITEM (toolbutton_debug), TRUE);

  tmp_image = gtk_image_new_from_stock ("gtk-stop", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton_stop = (GtkWidget*) gtk_tool_button_new (tmp_image, _("stop"));
  gtk_widget_set_name (toolbutton_stop, "toolbutton_stop");
  gtk_widget_show (toolbutton_stop);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_stop);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox1, "eventbox1");
  gtk_widget_show (eventbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), eventbox1, TRUE, TRUE, 0);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_set_name (hpaned1, "hpaned1");
  gtk_widget_show (hpaned1);
  gtk_container_add (GTK_CONTAINER (eventbox1), hpaned1);
  GTK_WIDGET_UNSET_FLAGS (hpaned1, GTK_CAN_FOCUS);
  gtk_paned_set_position (GTK_PANED (hpaned1), 200);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_show (notebook1);
  gtk_paned_pack1 (GTK_PANED (hpaned1), notebook1, FALSE, TRUE);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook1), GTK_POS_BOTTOM);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow5, "scrolledwindow5");
  gtk_widget_show (scrolledwindow5);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow5);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_set_name (treeview2, "treeview2");
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview2);

  label1 = gtk_label_new (_("Files"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox3);

  comboboxentry3 = gtk_combo_box_entry_new ();
  gtk_widget_set_name (comboboxentry3, "comboboxentry3");
  gtk_widget_show (comboboxentry3);
  gtk_box_pack_start (GTK_BOX (vbox3), comboboxentry3, FALSE, FALSE, 0);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar2, "toolbar2");
  gtk_widget_show (toolbar2);
  gtk_box_pack_start (GTK_BOX (vbox3), toolbar2, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2));

  toolbutton1 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-find");
  gtk_widget_set_name (toolbutton1, "toolbutton1");
  gtk_widget_show (toolbutton1);
  gtk_container_add (GTK_CONTAINER (toolbar2), toolbutton1);

  separatortoolitem4 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_set_name (separatortoolitem4, "separatortoolitem4");
  gtk_widget_show (separatortoolitem4);
  gtk_container_add (GTK_CONTAINER (toolbar2), separatortoolitem4);

  toolbutton2 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-find-and-replace");
  gtk_widget_set_name (toolbutton2, "toolbutton2");
  gtk_widget_show (toolbutton2);
  gtk_container_add (GTK_CONTAINER (toolbar2), toolbutton2);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow4, "scrolledwindow4");
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow4, TRUE, TRUE, 0);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_set_name (treeview1, "treeview1");
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview1);
  gtk_container_set_border_width (GTK_CONTAINER (treeview1), 1);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview1), TRUE);

  label2 = gtk_label_new (_("Rutines"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox4);

  toolbar3 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar3, "toolbar3");
  gtk_widget_show (toolbar3);
  gtk_box_pack_start (GTK_BOX (vbox4), toolbar3, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar3), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar3));

  toolbutton7 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-open");
  gtk_widget_set_name (toolbutton7, "toolbutton7");
  gtk_widget_show (toolbutton7);
  gtk_container_add (GTK_CONTAINER (toolbar3), toolbutton7);

  toolbutton8 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (toolbutton8, "toolbutton8");
  gtk_widget_show (toolbutton8);
  gtk_container_add (GTK_CONTAINER (toolbar3), toolbutton8);

  toolbutton9 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-add");
  gtk_widget_set_name (toolbutton9, "toolbutton9");
  gtk_widget_show (toolbutton9);
  gtk_container_add (GTK_CONTAINER (toolbar3), toolbutton9);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow6, "scrolledwindow6");
  gtk_widget_show (scrolledwindow6);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow6, TRUE, TRUE, 0);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_set_name (treeview3, "treeview3");
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), treeview3);

  label3 = gtk_label_new (_("Tools"));
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow7, "scrolledwindow7");
  gtk_widget_show (scrolledwindow7);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow7);

  textview1 = gtk_text_view_new ();
  gtk_widget_set_name (textview1, "textview1");
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), textview1);

  label4 = gtk_label_new (_("Help"));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_set_name (vpaned1, "vpaned1");
  gtk_widget_show (vpaned1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vpaned1, TRUE, TRUE);
  GTK_WIDGET_UNSET_FLAGS (vpaned1, GTK_CAN_FOCUS);
  gtk_paned_set_position (GTK_PANED (vpaned1), 400);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack1 (GTK_PANED (vpaned1), scrolledwindow1, FALSE, TRUE);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  textview_code = gtk_text_view_new ();
  gtk_widget_set_name (textview_code, "textview_code");
  gtk_widget_show (textview_code);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), textview_code);
  gtk_widget_set_extension_events (textview_code, GDK_EXTENSION_EVENTS_CURSOR);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_show (scrolledwindow2);
  gtk_paned_pack2 (GTK_PANED (vpaned1), scrolledwindow2, TRUE, TRUE);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  textview_output = gtk_text_view_new ();
  gtk_widget_set_name (textview_output, "textview_output");
  gtk_widget_show (textview_output);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textview_output);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview_output), FALSE);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar1, "statusbar1");
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) nuovo1, "activate",
                    G_CALLBACK (on_nuovo1_activate),
                    NULL);
  g_signal_connect ((gpointer) apri1, "activate",
                    G_CALLBACK (on_apri1_activate),
                    NULL);
  g_signal_connect ((gpointer) salva1, "activate",
                    G_CALLBACK (on_salva1_activate),
                    NULL);
  g_signal_connect ((gpointer) salva_come1, "activate",
                    G_CALLBACK (on_salva_come1_activate),
                    NULL);
  g_signal_connect ((gpointer) close1, "activate",
                    G_CALLBACK (on_close1_activate),
                    NULL);
  g_signal_connect ((gpointer) anteprima_di_stampa1, "activate",
                    G_CALLBACK (on_anteprima_di_stampa1_activate),
                    NULL);
  g_signal_connect ((gpointer) stampa1, "activate",
                    G_CALLBACK (on_stampa1_activate),
                    NULL);
  g_signal_connect ((gpointer) esci1, "activate",
                    G_CALLBACK (on_esci1_activate),
                    NULL);
  g_signal_connect ((gpointer) undo2, "activate",
                    G_CALLBACK (on_undo2_activate),
                    NULL);
  g_signal_connect ((gpointer) redo2, "activate",
                    G_CALLBACK (on_redo2_activate),
                    NULL);
  g_signal_connect ((gpointer) taglia1, "activate",
                    G_CALLBACK (on_taglia1_activate),
                    NULL);
  g_signal_connect ((gpointer) copia1, "activate",
                    G_CALLBACK (on_copia1_activate),
                    NULL);
  g_signal_connect ((gpointer) incolla1, "activate",
                    G_CALLBACK (on_incolla1_activate),
                    NULL);
  g_signal_connect ((gpointer) elimina1, "activate",
                    G_CALLBACK (on_elimina1_activate),
                    NULL);
  g_signal_connect ((gpointer) trova2, "activate",
                    G_CALLBACK (on_trova2_activate),
                    NULL);
  g_signal_connect ((gpointer) trova_e_sostituisci1, "activate",
                    G_CALLBACK (on_trova_e_sostituisci1_activate),
                    NULL);
  g_signal_connect ((gpointer) seleziona_tutto1, "activate",
                    G_CALLBACK (on_seleziona_tutto1_activate),
                    NULL);
  g_signal_connect ((gpointer) inverti_selezione1, "activate",
                    G_CALLBACK (on_inverti_selezione1_activate),
                    NULL);
  g_signal_connect ((gpointer) execute1, "activate",
                    G_CALLBACK (on_execute1_activate),
                    NULL);
  g_signal_connect ((gpointer) debug1, "activate",
                    G_CALLBACK (on_debug1_activate),
                    NULL);
  g_signal_connect ((gpointer) stop1, "activate",
                    G_CALLBACK (on_stop1_activate),
                    NULL);
  g_signal_connect ((gpointer) informazioni1, "activate",
                    G_CALLBACK (on_informazioni1_activate),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_nuovo, "clicked",
                    G_CALLBACK (on_toolbutton_nuovo_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_load, "clicked",
                    G_CALLBACK (on_toolbutton_load_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_salva, "clicked",
                    G_CALLBACK (on_toolbutton_salva_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_chiudi, "clicked",
                    G_CALLBACK (on_toolbutton_chiudi_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_undo, "clicked",
                    G_CALLBACK (on_toolbutton_undo_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_redo, "clicked",
                    G_CALLBACK (on_toolbutton_redo_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_execute, "clicked",
                    G_CALLBACK (on_toolbutton_run_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_debug, "clicked",
                    G_CALLBACK (on_toolbutton_debug_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_stop, "clicked",
                    G_CALLBACK (on_toolbutton_stop_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (main_window, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (main_window, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (main_window, nuovo1, "nuovo1");
  GLADE_HOOKUP_OBJECT (main_window, apri1, "apri1");
  GLADE_HOOKUP_OBJECT (main_window, salva1, "salva1");
  GLADE_HOOKUP_OBJECT (main_window, salva_come1, "salva_come1");
  GLADE_HOOKUP_OBJECT (main_window, close1, "close1");
  GLADE_HOOKUP_OBJECT (main_window, image61, "image61");
  GLADE_HOOKUP_OBJECT (main_window, separatore6, "separatore6");
  GLADE_HOOKUP_OBJECT (main_window, anteprima_di_stampa1, "anteprima_di_stampa1");
  GLADE_HOOKUP_OBJECT (main_window, image62, "image62");
  GLADE_HOOKUP_OBJECT (main_window, stampa1, "stampa1");
  GLADE_HOOKUP_OBJECT (main_window, image63, "image63");
  GLADE_HOOKUP_OBJECT (main_window, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (main_window, esci1, "esci1");
  GLADE_HOOKUP_OBJECT (main_window, menuitem5, "menuitem5");
  GLADE_HOOKUP_OBJECT (main_window, menuitem5_menu, "menuitem5_menu");
  GLADE_HOOKUP_OBJECT (main_window, undo2, "undo2");
  GLADE_HOOKUP_OBJECT (main_window, image64, "image64");
  GLADE_HOOKUP_OBJECT (main_window, redo2, "redo2");
  GLADE_HOOKUP_OBJECT (main_window, image65, "image65");
  GLADE_HOOKUP_OBJECT (main_window, separatore3, "separatore3");
  GLADE_HOOKUP_OBJECT (main_window, taglia1, "taglia1");
  GLADE_HOOKUP_OBJECT (main_window, copia1, "copia1");
  GLADE_HOOKUP_OBJECT (main_window, incolla1, "incolla1");
  GLADE_HOOKUP_OBJECT (main_window, elimina1, "elimina1");
  GLADE_HOOKUP_OBJECT (main_window, separatore4, "separatore4");
  GLADE_HOOKUP_OBJECT (main_window, trova2, "trova2");
  GLADE_HOOKUP_OBJECT (main_window, image66, "image66");
  GLADE_HOOKUP_OBJECT (main_window, trova_e_sostituisci1, "trova_e_sostituisci1");
  GLADE_HOOKUP_OBJECT (main_window, image67, "image67");
  GLADE_HOOKUP_OBJECT (main_window, separatore5, "separatore5");
  GLADE_HOOKUP_OBJECT (main_window, seleziona_tutto1, "seleziona_tutto1");
  GLADE_HOOKUP_OBJECT (main_window, inverti_selezione1, "inverti_selezione1");
  GLADE_HOOKUP_OBJECT (main_window, run1, "run1");
  GLADE_HOOKUP_OBJECT (main_window, run1_menu, "run1_menu");
  GLADE_HOOKUP_OBJECT (main_window, execute1, "execute1");
  GLADE_HOOKUP_OBJECT (main_window, image68, "image68");
  GLADE_HOOKUP_OBJECT (main_window, debug1, "debug1");
  GLADE_HOOKUP_OBJECT (main_window, image69, "image69");
  GLADE_HOOKUP_OBJECT (main_window, stop1, "stop1");
  GLADE_HOOKUP_OBJECT (main_window, image70, "image70");
  GLADE_HOOKUP_OBJECT (main_window, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (main_window, menuitem7_menu, "menuitem7_menu");
  GLADE_HOOKUP_OBJECT (main_window, informazioni1, "informazioni1");
  GLADE_HOOKUP_OBJECT (main_window, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton_nuovo, "toolbutton_nuovo");
  GLADE_HOOKUP_OBJECT (main_window, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton_load, "toolbutton_load");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton_salva, "toolbutton_salva");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton_chiudi, "toolbutton_chiudi");
  GLADE_HOOKUP_OBJECT (main_window, separatortoolitem2, "separatortoolitem2");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton_undo, "toolbutton_undo");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton_redo, "toolbutton_redo");
  GLADE_HOOKUP_OBJECT (main_window, separatortoolitem3, "separatortoolitem3");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton_execute, "toolbutton_execute");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton_debug, "toolbutton_debug");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton_stop, "toolbutton_stop");
  GLADE_HOOKUP_OBJECT (main_window, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (main_window, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (main_window, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (main_window, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (main_window, label1, "label1");
  GLADE_HOOKUP_OBJECT (main_window, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (main_window, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (main_window, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton1, "toolbutton1");
  GLADE_HOOKUP_OBJECT (main_window, separatortoolitem4, "separatortoolitem4");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton2, "toolbutton2");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (main_window, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (main_window, label2, "label2");
  GLADE_HOOKUP_OBJECT (main_window, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (main_window, toolbar3, "toolbar3");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton7, "toolbutton7");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton8, "toolbutton8");
  GLADE_HOOKUP_OBJECT (main_window, toolbutton9, "toolbutton9");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (main_window, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (main_window, label3, "label3");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (main_window, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (main_window, label4, "label4");
  GLADE_HOOKUP_OBJECT (main_window, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (main_window, textview_code, "textview_code");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (main_window, textview_output, "textview_output");
  GLADE_HOOKUP_OBJECT (main_window, statusbar1, "statusbar1");

  gtk_widget_grab_focus (textview_code);
  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_fileloaddialog (void)
{
  GtkWidget *fileloaddialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *button1;
  GtkWidget *button2;

  fileloaddialog = gtk_file_chooser_dialog_new (_("open file"), NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_widget_set_name (fileloaddialog, "fileloaddialog");
  GTK_WIDGET_SET_FLAGS (fileloaddialog, GTK_CAN_FOCUS);
  g_object_set (fileloaddialog,
                "select-multiple", TRUE,
                "show-hidden", TRUE,
                NULL);
  gtk_window_set_position (GTK_WINDOW (fileloaddialog), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_modal (GTK_WINDOW (fileloaddialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (fileloaddialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (fileloaddialog)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (fileloaddialog)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  button1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (button1, "button1");
  gtk_widget_show (button1);
  gtk_dialog_add_action_widget (GTK_DIALOG (fileloaddialog), button1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_set_name (button2, "button2");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (fileloaddialog), button2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fileloaddialog, fileloaddialog, "fileloaddialog");
  GLADE_HOOKUP_OBJECT_NO_REF (fileloaddialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (fileloaddialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (fileloaddialog, button1, "button1");
  GLADE_HOOKUP_OBJECT (fileloaddialog, button2, "button2");

  gtk_widget_grab_default (button2);
  return fileloaddialog;
}

GtkWidget*
create_filesavedialog (void)
{
  GtkWidget *filesavedialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *dialog_action_area2;
  GtkWidget *button3;
  GtkWidget *button4;

  filesavedialog = gtk_file_chooser_dialog_new (_("save file"), NULL, GTK_FILE_CHOOSER_ACTION_SAVE, NULL);
  gtk_widget_set_name (filesavedialog, "filesavedialog");
  GTK_WIDGET_SET_FLAGS (filesavedialog, GTK_CAN_FOCUS);
  g_object_set (filesavedialog,
                "show-hidden", TRUE,
                NULL);
  gtk_window_set_modal (GTK_WINDOW (filesavedialog), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (filesavedialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (filesavedialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (filesavedialog)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_widget_show (dialog_vbox2);

  dialog_action_area2 = GTK_DIALOG (filesavedialog)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  button3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (button3, "button3");
  gtk_widget_show (button3);
  gtk_dialog_add_action_widget (GTK_DIALOG (filesavedialog), button3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  button4 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_set_name (button4, "button4");
  gtk_widget_show (button4);
  gtk_dialog_add_action_widget (GTK_DIALOG (filesavedialog), button4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filesavedialog, filesavedialog, "filesavedialog");
  GLADE_HOOKUP_OBJECT_NO_REF (filesavedialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT_NO_REF (filesavedialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (filesavedialog, button3, "button3");
  GLADE_HOOKUP_OBJECT (filesavedialog, button4, "button4");

  gtk_widget_grab_default (button4);
  return filesavedialog;
}

